### ISSUE TITLE
License

### ISSUE THREAD

**Issue by yatima1460** [mhousse1247/UE4-CustomGravityPlugin#4]
You should add a license file for this project

I recommend a GPL v2.0

**Comment by ericwomer** [comment]
They can't, as it thankfully violates Epics EULA.

**Comment by yatima1460** [comment]
A plugin license is different from the Unreal license.
You **own** your plugin code, not Epic

**Comment by ericwomer** [comment]
Not completely accurate, https://answers.unrealengine.com/questions/321377/dual-licensing-engine-plugins.html can not be under a non-compatible license.

**Comment by ericwomer** [comment]
Non-Compatible Licenses

You may not combine, Distribute, or otherwise use the Licensed Technology with any code or other content which is covered by a license that would directly or indirectly require that all or part of the Licensed Technology be governed under any terms other than those of this Agreement (“Non-Compatible License”). Code or content under the following licenses, for example, are prohibited: GNU General Public License (GPL), Lesser GPL (LGPL) (unless you are merely dynamically linking a shared library), or Creative Commons Attribution-ShareAlike License. Code or content under the following licenses, for example, are allowed: BSD License, MIT License, Microsoft Public License, or Apache License. You may not sublicense the Licensed Technology under a Non-Compatible License.

**Comment by yatima1460** [comment]
> unless you are merely dynamically linking a shared library

So theoretically you can use the GPLv2 if you dynamically link a plugin?

**Comment by davidsaulrodriguez** [comment]
Why not just license this under the BSD-2-Clause or BSD-3-Clause license and call it a day?

**Comment by devonak** [comment]
Can this be used commercially?

**Comment by davidsaulrodriguez** [comment]
I don't see why not. Seeing as the code for this plugin itself is open source and there is no license restricting such use. @mhousse1247  just hasn't applied a license yet. A BSD, MIT or Apache license would do. But it is solely up to the author of this code!

Of course, 5% royalties come into play when you are using the Unreal Engine for your game and when it is sold commercially but that is between you and Epic Games.

**Comment by HoussineMehnik** [comment]
I just added a MIT licence.
Like @davidsrodriguez mentioned , from my side the project & code is free to use whatever the purpose.
